[theme]

# Primary accent for interactive elements
primaryColor = '#D61325'

# Background color for the main content area
backgroundColor = '#354A7C'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#1B8E7D'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"


